import type { StructureGraphData } from './types.js';

export const sampleGraphData: StructureGraphData = {
  projectRoot: '/example/react-dependency-graph',
  scannedAt: '2026-05-30T00:00:00.000Z',
  totalFiles: 7,
  totalDirs: 5,
  nodes: [
    {
      id: '/example/react-dependency-graph',
      label: 'react-dependency-graph',
      relativePath: '.',
      absolutePath: '/example/react-dependency-graph',
      kind: 'directory',
      extension: null,
      depth: 0,
      collapsed: false,
      hidden: false,
      childCount: 3,
      descendantCount: 11,
    },
    {
      id: '/example/react-dependency-graph/src',
      label: 'src',
      relativePath: 'src',
      absolutePath: '/example/react-dependency-graph/src',
      kind: 'directory',
      extension: null,
      depth: 1,
      collapsed: false,
      hidden: false,
      childCount: 3,
      descendantCount: 6,
    },
    {
      id: '/example/react-dependency-graph/src/components',
      label: 'components',
      relativePath: 'src/components',
      absolutePath: '/example/react-dependency-graph/src/components',
      kind: 'directory',
      extension: null,
      depth: 2,
      collapsed: false,
      hidden: false,
      childCount: 2,
      descendantCount: 2,
    },
    {
      id: '/example/react-dependency-graph/src/components/GraphView.tsx',
      label: 'GraphView.tsx',
      relativePath: 'src/components/GraphView.tsx',
      absolutePath: '/example/react-dependency-graph/src/components/GraphView.tsx',
      kind: 'file',
      extension: '.tsx',
      depth: 3,
      collapsed: false,
      hidden: false,
      childCount: 0,
      descendantCount: 0,
      sizeBytes: 5620,
    },
    {
      id: '/example/react-dependency-graph/src/components/Toolbar.tsx',
      label: 'Toolbar.tsx',
      relativePath: 'src/components/Toolbar.tsx',
      absolutePath: '/example/react-dependency-graph/src/components/Toolbar.tsx',
      kind: 'file',
      extension: '.tsx',
      depth: 3,
      collapsed: false,
      hidden: false,
      childCount: 0,
      descendantCount: 0,
      sizeBytes: 2310,
    },
    {
      id: '/example/react-dependency-graph/src/hooks',
      label: 'hooks',
      relativePath: 'src/hooks',
      absolutePath: '/example/react-dependency-graph/src/hooks',
      kind: 'directory',
      extension: null,
      depth: 2,
      collapsed: false,
      hidden: false,
      childCount: 1,
      descendantCount: 1,
    },
    {
      id: '/example/react-dependency-graph/src/hooks/useGraphData.ts',
      label: 'useGraphData.ts',
      relativePath: 'src/hooks/useGraphData.ts',
      absolutePath: '/example/react-dependency-graph/src/hooks/useGraphData.ts',
      kind: 'file',
      extension: '.ts',
      depth: 3,
      collapsed: false,
      hidden: false,
      childCount: 0,
      descendantCount: 0,
      sizeBytes: 1220,
    },
    {
      id: '/example/react-dependency-graph/src/App.tsx',
      label: 'App.tsx',
      relativePath: 'src/App.tsx',
      absolutePath: '/example/react-dependency-graph/src/App.tsx',
      kind: 'file',
      extension: '.tsx',
      depth: 2,
      collapsed: false,
      hidden: false,
      childCount: 0,
      descendantCount: 0,
      sizeBytes: 3011,
    },
    {
      id: '/example/react-dependency-graph/package.json',
      label: 'package.json',
      relativePath: 'package.json',
      absolutePath: '/example/react-dependency-graph/package.json',
      kind: 'file',
      extension: '.json',
      depth: 1,
      collapsed: false,
      hidden: false,
      childCount: 0,
      descendantCount: 0,
      sizeBytes: 842,
    },
    {
      id: '/example/react-dependency-graph/public',
      label: 'public',
      relativePath: 'public',
      absolutePath: '/example/react-dependency-graph/public',
      kind: 'directory',
      extension: null,
      depth: 1,
      collapsed: false,
      hidden: false,
      childCount: 2,
      descendantCount: 2,
    },
    {
      id: '/example/react-dependency-graph/public/graph-data.json',
      label: 'graph-data.json',
      relativePath: 'public/graph-data.json',
      absolutePath: '/example/react-dependency-graph/public/graph-data.json',
      kind: 'file',
      extension: '.json',
      depth: 2,
      collapsed: false,
      hidden: false,
      childCount: 0,
      descendantCount: 0,
      sizeBytes: 10950,
    },
    {
      id: '/example/react-dependency-graph/public/index.html',
      label: 'index.html',
      relativePath: 'public/index.html',
      absolutePath: '/example/react-dependency-graph/public/index.html',
      kind: 'file',
      extension: '.html',
      depth: 2,
      collapsed: false,
      hidden: false,
      childCount: 0,
      descendantCount: 0,
      sizeBytes: 711,
    },
  ],
  edges: [
    {
      id: '/example/react-dependency-graph->/example/react-dependency-graph/src',
      source: '/example/react-dependency-graph',
      target: '/example/react-dependency-graph/src',
    },
    {
      id: '/example/react-dependency-graph->/example/react-dependency-graph/package.json',
      source: '/example/react-dependency-graph',
      target: '/example/react-dependency-graph/package.json',
    },
    {
      id: '/example/react-dependency-graph->/example/react-dependency-graph/public',
      source: '/example/react-dependency-graph',
      target: '/example/react-dependency-graph/public',
    },
    {
      id: '/example/react-dependency-graph/src->/example/react-dependency-graph/src/components',
      source: '/example/react-dependency-graph/src',
      target: '/example/react-dependency-graph/src/components',
    },
    {
      id: '/example/react-dependency-graph/src->/example/react-dependency-graph/src/hooks',
      source: '/example/react-dependency-graph/src',
      target: '/example/react-dependency-graph/src/hooks',
    },
    {
      id: '/example/react-dependency-graph/src->/example/react-dependency-graph/src/App.tsx',
      source: '/example/react-dependency-graph/src',
      target: '/example/react-dependency-graph/src/App.tsx',
    },
    {
      id: '/example/react-dependency-graph/src/components->/example/react-dependency-graph/src/components/GraphView.tsx',
      source: '/example/react-dependency-graph/src/components',
      target: '/example/react-dependency-graph/src/components/GraphView.tsx',
    },
    {
      id: '/example/react-dependency-graph/src/components->/example/react-dependency-graph/src/components/Toolbar.tsx',
      source: '/example/react-dependency-graph/src/components',
      target: '/example/react-dependency-graph/src/components/Toolbar.tsx',
    },
    {
      id: '/example/react-dependency-graph/src/hooks->/example/react-dependency-graph/src/hooks/useGraphData.ts',
      source: '/example/react-dependency-graph/src/hooks',
      target: '/example/react-dependency-graph/src/hooks/useGraphData.ts',
    },
    {
      id: '/example/react-dependency-graph/public->/example/react-dependency-graph/public/graph-data.json',
      source: '/example/react-dependency-graph/public',
      target: '/example/react-dependency-graph/public/graph-data.json',
    },
    {
      id: '/example/react-dependency-graph/public->/example/react-dependency-graph/public/index.html',
      source: '/example/react-dependency-graph/public',
      target: '/example/react-dependency-graph/public/index.html',
    },
  ],
};
