import type { ExplorerGraphData, ExplorerGraphSet } from './types.js';
import packageJson from '../package.json';

export const sampleGraphData: ExplorerGraphData = {
  schemaVersion: '1.0.0',
  mode: 'structure',
  projectRoot: '/example/depxray',
  scannedAt: '2026-05-30T00:00:00.000Z',
  totalFiles: 7,
  totalDirs: 5,
  totalImports: 0,
  circularCount: 0,
  circularDependencies: [],
  orphanFiles: [],
  unresolvedImports: [],
  generatedBy: `depxray@${packageJson.version}`,
  errors: [],
  nodes: [
    {
      id: '/example/depxray',
      label: 'depxray',
      relativePath: '.',
      absolutePath: '/example/depxray',
      kind: 'directory',
      extension: null,
      depth: 0,
      collapsed: false,
      hidden: false,
      childCount: 3,
      descendantCount: 11,
    },
    {
      id: '/example/depxray/src',
      label: 'src',
      relativePath: 'src',
      absolutePath: '/example/depxray/src',
      kind: 'directory',
      extension: null,
      depth: 1,
      collapsed: false,
      hidden: false,
      childCount: 3,
      descendantCount: 6,
    },
    {
      id: '/example/depxray/src/components',
      label: 'components',
      relativePath: 'src/components',
      absolutePath: '/example/depxray/src/components',
      kind: 'directory',
      extension: null,
      depth: 2,
      collapsed: false,
      hidden: false,
      childCount: 2,
      descendantCount: 2,
    },
    {
      id: '/example/depxray/src/components/GraphView.tsx',
      label: 'GraphView.tsx',
      relativePath: 'src/components/GraphView.tsx',
      absolutePath: '/example/depxray/src/components/GraphView.tsx',
      kind: 'file',
      extension: '.tsx',
      depth: 3,
      collapsed: false,
      hidden: false,
      childCount: 0,
      descendantCount: 0,
      sizeBytes: 5620,
    },
    {
      id: '/example/depxray/src/components/Toolbar.tsx',
      label: 'Toolbar.tsx',
      relativePath: 'src/components/Toolbar.tsx',
      absolutePath: '/example/depxray/src/components/Toolbar.tsx',
      kind: 'file',
      extension: '.tsx',
      depth: 3,
      collapsed: false,
      hidden: false,
      childCount: 0,
      descendantCount: 0,
      sizeBytes: 2310,
    },
    {
      id: '/example/depxray/src/hooks',
      label: 'hooks',
      relativePath: 'src/hooks',
      absolutePath: '/example/depxray/src/hooks',
      kind: 'directory',
      extension: null,
      depth: 2,
      collapsed: false,
      hidden: false,
      childCount: 1,
      descendantCount: 1,
    },
    {
      id: '/example/depxray/src/hooks/useGraphData.ts',
      label: 'useGraphData.ts',
      relativePath: 'src/hooks/useGraphData.ts',
      absolutePath: '/example/depxray/src/hooks/useGraphData.ts',
      kind: 'file',
      extension: '.ts',
      depth: 3,
      collapsed: false,
      hidden: false,
      childCount: 0,
      descendantCount: 0,
      sizeBytes: 1220,
    },
    {
      id: '/example/depxray/src/App.tsx',
      label: 'App.tsx',
      relativePath: 'src/App.tsx',
      absolutePath: '/example/depxray/src/App.tsx',
      kind: 'file',
      extension: '.tsx',
      depth: 2,
      collapsed: false,
      hidden: false,
      childCount: 0,
      descendantCount: 0,
      sizeBytes: 3011,
    },
    {
      id: '/example/depxray/package.json',
      label: 'package.json',
      relativePath: 'package.json',
      absolutePath: '/example/depxray/package.json',
      kind: 'file',
      extension: '.json',
      depth: 1,
      collapsed: false,
      hidden: false,
      childCount: 0,
      descendantCount: 0,
      sizeBytes: 842,
    },
    {
      id: '/example/depxray/public',
      label: 'public',
      relativePath: 'public',
      absolutePath: '/example/depxray/public',
      kind: 'directory',
      extension: null,
      depth: 1,
      collapsed: false,
      hidden: false,
      childCount: 2,
      descendantCount: 2,
    },
    {
      id: '/example/depxray/public/graph-data.json',
      label: 'graph-data.json',
      relativePath: 'public/graph-data.json',
      absolutePath: '/example/depxray/public/graph-data.json',
      kind: 'file',
      extension: '.json',
      depth: 2,
      collapsed: false,
      hidden: false,
      childCount: 0,
      descendantCount: 0,
      sizeBytes: 10950,
    },
    {
      id: '/example/depxray/public/index.html',
      label: 'index.html',
      relativePath: 'public/index.html',
      absolutePath: '/example/depxray/public/index.html',
      kind: 'file',
      extension: '.html',
      depth: 2,
      collapsed: false,
      hidden: false,
      childCount: 0,
      descendantCount: 0,
      sizeBytes: 711,
    },
  ],
  edges: [
    {
      id: '/example/depxray->/example/depxray/src',
      source: '/example/depxray',
      target: '/example/depxray/src',
      kind: 'structure',
    },
    {
      id: '/example/depxray->/example/depxray/package.json',
      source: '/example/depxray',
      target: '/example/depxray/package.json',
      kind: 'structure',
    },
    {
      id: '/example/depxray->/example/depxray/public',
      source: '/example/depxray',
      target: '/example/depxray/public',
      kind: 'structure',
    },
    {
      id: '/example/depxray/src->/example/depxray/src/components',
      source: '/example/depxray/src',
      target: '/example/depxray/src/components',
      kind: 'structure',
    },
    {
      id: '/example/depxray/src->/example/depxray/src/hooks',
      source: '/example/depxray/src',
      target: '/example/depxray/src/hooks',
      kind: 'structure',
    },
    {
      id: '/example/depxray/src->/example/depxray/src/App.tsx',
      source: '/example/depxray/src',
      target: '/example/depxray/src/App.tsx',
      kind: 'structure',
    },
    {
      id: '/example/depxray/src/components->/example/depxray/src/components/GraphView.tsx',
      source: '/example/depxray/src/components',
      target: '/example/depxray/src/components/GraphView.tsx',
      kind: 'structure',
    },
    {
      id: '/example/depxray/src/components->/example/depxray/src/components/Toolbar.tsx',
      source: '/example/depxray/src/components',
      target: '/example/depxray/src/components/Toolbar.tsx',
      kind: 'structure',
    },
    {
      id: '/example/depxray/src/hooks->/example/depxray/src/hooks/useGraphData.ts',
      source: '/example/depxray/src/hooks',
      target: '/example/depxray/src/hooks/useGraphData.ts',
      kind: 'structure',
    },
    {
      id: '/example/depxray/public->/example/depxray/public/graph-data.json',
      source: '/example/depxray/public',
      target: '/example/depxray/public/graph-data.json',
      kind: 'structure',
    },
    {
      id: '/example/depxray/public->/example/depxray/public/index.html',
      source: '/example/depxray/public',
      target: '/example/depxray/public/index.html',
      kind: 'structure',
    },
  ],
};

const sampleDependencyEdges: ExplorerGraphData['edges'] = [
  {
    id: 'app-to-graph',
    source: '/example/depxray/src/App.tsx',
    target: '/example/depxray/src/components/GraphView.tsx',
    kind: 'dependencies',
    importSpecifier: './components/GraphView.js',
    importedNames: ['GraphView'],
    isTypeOnly: false,
    isDynamic: false,
  },
  {
    id: 'app-to-toolbar',
    source: '/example/depxray/src/App.tsx',
    target: '/example/depxray/src/components/Toolbar.tsx',
    kind: 'dependencies',
    importSpecifier: './components/Toolbar.js',
    importedNames: ['Toolbar'],
    isTypeOnly: false,
    isDynamic: false,
  },
  {
    id: 'app-to-hook',
    source: '/example/depxray/src/App.tsx',
    target: '/example/depxray/src/hooks/useGraphData.ts',
    kind: 'dependencies',
    importSpecifier: './hooks/useGraphData.js',
    importedNames: ['useGraphData'],
    isTypeOnly: false,
    isDynamic: false,
  },
];

export const sampleDependencyGraphData: ExplorerGraphData = {
  ...sampleGraphData,
  mode: 'dependencies',
  totalDirs: 0,
  totalImports: sampleDependencyEdges.length,
  healthScore: {
    grade: 'B',
    score: 84,
    issues: {
      circularChains: 0,
      orphanFiles: 1,
      unusedExports: 2,
      unresolvedImports: 0,
      ruleViolations: 0,
    },
    hotspots: [
      { file: 'src/components/GraphView.tsx', complexity: 18, loc: 286 },
      { file: 'src/hooks/useGraphData.ts', complexity: 12, loc: 154 },
      { file: 'src/components/Toolbar.tsx', complexity: 8, loc: 118 },
      { file: 'src/App.tsx', complexity: 6, loc: 92 },
    ],
    hubs: [
      { file: 'src/components/GraphView.tsx', inDegree: 8, outDegree: 3 },
      { file: 'src/components/Toolbar.tsx', inDegree: 5, outDegree: 1 },
      { file: 'src/hooks/useGraphData.ts', inDegree: 4, outDegree: 2 },
      { file: 'src/App.tsx', inDegree: 1, outDegree: 3 },
    ],
  },
  nodes: sampleGraphData.nodes
    .filter((node) => node.kind === 'file' && ['.ts', '.tsx'].includes(node.extension ?? ''))
    .map((node) => ({
      ...node,
      inDegree: sampleDependencyEdges.filter((edge) => edge.target === node.id).length,
      outDegree: sampleDependencyEdges.filter((edge) => edge.source === node.id).length,
      isCircular: false,
      isOrphan: node.id === '/example/depxray/src/App.tsx',
    })),
  edges: sampleDependencyEdges,
};

export const sampleGraphSet: ExplorerGraphSet = {
  schemaVersion: sampleGraphData.schemaVersion,
  generatedBy: sampleGraphData.generatedBy,
  projectRoot: sampleGraphData.projectRoot,
  scannedAt: sampleGraphData.scannedAt,
  availableModes: ['structure', 'dependencies'],
  defaultMode: 'structure',
  graphs: {
    structure: sampleGraphData,
    dependencies: sampleDependencyGraphData,
  },
};
